import { sqliteTable, integer, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

export const schools = sqliteTable(
  "schools",
  {
    schoolId: text("school_id").primaryKey(),
    name: text("name").notNull(),
    schoolCode: text("school_code"),
    type: text("type"),
    typeText: text("type_text"),
    typeSchoolText: text("type_school_text"),
    is211: integer("is_211").notNull().default(0),
    is985: integer("is_985").notNull().default(0),
    isDualClass: integer("is_dual_class").notNull().default(0),
    provinceText: text("province_text"),
    provinceAreaText: text("province_area_text"),
    belongsTo: text("belongs_to"),
    schoolAddress: text("school_address"),
    rank: integer("rank"),
    logo: text("logo"),
    sourceOid: text("source_oid"),
    rawDetail: text("raw_detail"),
  },
  (t) => ({
    uqName: uniqueIndex("uq_schools_name").on(t.name),
    idxCode: index("idx_schools_code").on(t.schoolCode),
  }),
);

export const admissions = sqliteTable(
  "admissions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    year: integer("year").notNull(),
    province: text("province").notNull(),
    batch: text("batch").notNull(),
    enrollType: text("enroll_type").notNull(),
    subjectGroup: text("subject_group").notNull(),
    schoolCode: text("school_code").notNull(),
    schoolName: text("school_name").notNull(),
    schoolCity: text("school_city"),
    schoolOwner: text("school_owner"),
    schoolRefId: text("school_ref_id").references(() => schools.schoolId),
    majorCode: text("major_code").notNull(),
    majorName: text("major_name").notNull(),
    minScore: integer("min_score"),
    tieChinMathSum: integer("tie_chin_math_sum"),
    tieChinMathMax: integer("tie_chin_math_max"),
    tieForeign: integer("tie_foreign"),
    tiePrimarySubj: integer("tie_primary_subj"),
    tieSecondaryMax: integer("tie_secondary_max"),
    tieSecondary2nd: integer("tie_secondary_2nd"),
    tieVolunteerNo: integer("tie_volunteer_no"),
    remark: text("remark"),
    sourceFile: text("source_file").notNull(),
  },
  (t) => ({
    uq: uniqueIndex("uq_admissions_year_group_school_major").on(
      t.year,
      t.subjectGroup,
      t.schoolCode,
      t.majorCode,
    ),
    idxGroupScore: index("idx_admissions_group_score").on(t.subjectGroup, t.minScore),
    idxSchoolCode: index("idx_admissions_school_code").on(t.schoolCode),
    idxSchoolName: index("idx_admissions_school_name").on(t.schoolName),
    idxRef: index("idx_admissions_school_ref").on(t.schoolRefId),
  }),
);
